apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/counter-pv
  storageClassName: standard
