apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-claim
  namespace: default
  labels:
    app: counter
spec:
  volumeName: counter-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
